In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df = pd.read_excel("First Dataset.xlsx")

In [ ]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [ ]:
df[df["age"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
19,1020,Kimia,M,NaN,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,Yes,1,5

In [ ]:
df["age"].describe()

count     60.000000
mean      45.200000
std       19.167239
min       19.000000
25%       31.750000
50%       45.000000
75%       58.000000
max      145.000000
Name: age, dtype: float64

In [ ]:
df[df["age"]>100]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [ ]:
df.loc[df["age"] <=100, "age"].describe()

count    59.000000
mean     43.508475
std      14.109636
min      19.000000
25%      31.500000
50%      45.000000
75%      58.000000
max      65.000000
Name: age, dtype: float64

In [ ]:
import numpy as np

In [ ]:
df.loc[df["age"] > 100, "age"] = np.nan

In [ ]:
df["age"].isna().sum()

np.int64(2)

In [ ]:
df["age"].median()

45.0

In [ ]:
df["age"] = df["age"].fillna(df["age"].median())

In [ ]:
df["age"].isna().sum()

np.int64(0)

In [ ]:
df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [ ]:
df[df["total_spending"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [ ]:
df[["purchase_count", "avg_order_value", "total_spending"]].head(10)

   purchase_count  avg_order_value  total_spending
0              17           121.53         2066.01
1              12           326.47         3917.64
2              21            59.46         1248.66
3              23           266.15         6121.45
4              23           169.54         3899.42
5              35           110.53         3868.55
6              29            77.15         2237.35
7               3           389.58         1168.74
8              34           341.63        11615.42
9              19           381.13         7241.47

In [ ]:
df.loc[df["total_spending"].isna(), "total_spending"] = (df["purchase_count"] * df["avg_order_value"])

In [ ]:
df["total_spending"].isna().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated(keep=False)]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     object
 2   gender              60 non-null     object
 3   age                 60 non-null     float64
 4   city                60 non-null     object
 5   province            60 non-null     object
 6   signup_date         60 non-null     object
 7   membership_tier     60 non-null     object
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     object
 13  device              60 non-null     object
 14  discount_used       60 non-null     object
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.4+ KB

In [ ]:
df["age"] = df["age"].astype(int)
df["age"].dtype
df = df.copy()

/tmp/ipykernel_1244/1297209307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["age"] = df["age"].astype(int)

In [ ]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [ ]:
df["signup_date"].dtype

dtype('<M8[ns]')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     object
 2   gender              60 non-null     object
 3   age                 60 non-null     int64
 4   city                60 non-null     object
 5   province            60 non-null     object
 6   signup_date         60 non-null     datetime64[ns]
 7   membership_tier     60 non-null     object
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     object
 13  device              60 non-null     object
 14  discount_used       60 non-null     object
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: datetime64[ns](1), float64(2), int64(6), object(8)
memory usage: 8.4+ KB

In [ ]:
df["signup_date"].head(10)

0   2025-02-19
1   2022-08-19
2   2023-06-20
3   2021-11-08
4   2021-10-21
5   2022-01-26
6   2025-09-09
7   2024-10-03
8   2021-05-14
9   2022-06-25
Name: signup_date, dtype: datetime64[ns]

In [ ]:
df["signup_date"].isna().sum()

np.int64(0)

In [ ]:
df.describe()

,customer_id,age,signup_date,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,60.000000,60.000000,60,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,1030.500000,43.700000,2023-02-03 14:00:00,17.383333,213.156500,3715.109833,198.600000,4.183333,2.983333
min,1001.000000,19.000000,2021-02-23 00:00:00,0.000000,27.630000,0.000000,3.000000,0.000000,1.000000
25%,1015.750000,31.750000,2021-12-06 12:00:00,10.750000,108.137500,1167.035000,134.250000,2.000000,2.000000
50%,1030.500000,45.000000,2022-08-15 00:00:00,17.000000,165.435000,2128.690000,203.000000,4.000000,3.000000
75%,1045.250000,58.000000,2024-06-14 12:00:00,24.500000,324.107500,4692.150000,273.750000,7.000000,4.000000
max,1060.000000,65.000000,2025-09-09 00:00:00,35.000000,449.810000,25000.000000,365.000000,8.000000,5.000000
std,17.464249,13.946994,NaN,10.149880,130.509923,4273.901437,97.843043,2.683861,1.431979

In [ ]:
df[df["total_spending"] == 25000]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4

In [ ]:
df["expected_spending"] = df["purchase_count"] * df["avg_order_value"]
df[["total_spending", "expected_spending"]].head()

   total_spending  expected_spending
0         2066.01            2066.01
1         3917.64            3917.64
2         1248.66            1248.66
3         6121.45            6121.45
4         3899.42            3899.42

In [ ]:
df.loc[df["total_spending"] == 25000, "total_spendig"] = np.nan
df.loc[df["total_spending"].isna(), "total_spending"] = (
    df["purchase_count"] * df["avg_order_value"]
)

In [ ]:
df.describe()

,customer_id,age,signup_date,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,60.000000,60.000000,60,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,1030.500000,43.700000,2023-02-03 14:00:00,17.383333,213.156500,3366.428833,198.600000,4.183333,2.983333
min,1001.000000,19.000000,2021-02-23 00:00:00,0.000000,27.630000,0.000000,3.000000,0.000000,1.000000
25%,1015.750000,31.750000,2021-12-06 12:00:00,10.750000,108.137500,1167.035000,134.250000,2.000000,2.000000
50%,1030.500000,45.000000,2022-08-15 00:00:00,17.000000,165.435000,2128.690000,203.000000,4.000000,3.000000
75%,1045.250000,58.000000,2024-06-14 12:00:00,24.500000,324.107500,4213.117500,273.750000,7.000000,4.000000
max,1060.000000,65.000000,2025-09-09 00:00:00,35.000000,449.810000,14354.340000,365.000000,8.000000,5.000000
std,17.464249,13.946994,NaN,10.149880,130.509923,3235.132979,97.843043,2.683861,1.431979

In [ ]:
for col in df.select_dtypes(include="object").columns:
  print(col)
  print(df[col].unique())
  print()

first_name
['Reza' 'Sina' 'Parsa' 'Kimia' 'Amir' 'Arash' 'Neda' 'Ali' 'Mina' 'Zahra'
 'Maryam' 'Sara']

gender
['F' 'M']

city
['Karaj' 'Tehran' 'Shiraz' 'Mashhad' 'Isfahan' 'Rasht' 'Tabriz' 'Ahvaz']

province
['Alborz' 'Tehran' 'Fars' 'Khorasan' 'Isfahan' 'Gilan' 'East Azerbaijan'
 'Khuzestan']

membership_tier
['VIP' 'Gold' 'Silver' 'Bronze']

payment_method
['Card' 'Online Wallet' 'Cash']

device
['Android' 'Web' 'iPhone']

discount_used
['Yes' 'No']

In [ ]:
for col in df.select_dtypes(include="object").columns:
  df[col] = df[col].str.strip()

In [ ]:
df[df["returned_items"] > df["purchase_count"]][
    ["customer_id", "purchase_count", "returned_items"]
]

    customer_id  purchase_count  returned_items
7        1008.0             3.0             8.0
14       1015.0             3.0             8.0
23       1024.0             0.0             2.0
28       1029.0             2.0             4.0
36       1037.0             1.0             7.0
55       1056.0             1.0             4.0

In [ ]:
df.loc[df["returned_items"] > df["purchase_count"], "returned_items"] = np.nan

In [ ]:
df["returned_items"].isna().sum()

np.int64(6)

In [ ]:
df["returned_items"].describe()

count    54.000000
mean      4.037037
std       2.684427
min       0.000000
25%       2.000000
50%       4.000000
75%       6.750000
max       8.000000
Name: returned_items, dtype: float64

In [ ]:
df.to_excel("cleaned_dataset.xlsx", index=False)